// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: savourrpc/wallet.proto

package wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetSupportCoins(ctx context.Context, in *SupportCoinsRequest, opts ...grpc.CallOption) (*SupportCoinsResponse, error)
	ConvertAddress(ctx context.Context, in *ConvertAddressRequest, opts ...grpc.CallOption) (*ConvertAddressResponse, error)
	ValidAddress(ctx context.Context, in *ValidAddressRequest, opts ...grpc.CallOption) (*ValidAddressResponse, error)
	GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	GetNonce(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error)
	GetGasPrice(ctx context.Context, in *GasPriceRequest, opts ...grpc.CallOption) (*GasPriceResponse, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetMinRent(ctx context.Context, in *MinRentRequest, opts ...grpc.CallOption) (*MinRentResponse, error)
	SendTx(ctx context.Context, in *SendTxRequest, opts ...grpc.CallOption) (*SendTxResponse, error)
	GetTxByAddress(ctx context.Context, in *TxAddressRequest, opts ...grpc.CallOption) (*TxAddressResponse, error)
	GetTxByHash(ctx context.Context, in *TxHashRequest, opts ...grpc.CallOption) (*TxHashResponse, error)
	GetUtxo(ctx context.Context, in *UtxoRequest, opts ...grpc.CallOption) (*UtxoResponse, error)
	GetUnspentOutputs(ctx context.Context, in *UnspentOutputsRequest, opts ...grpc.CallOption) (*UnspentOutputsResponse, error)
	GetUtxoInsFromData(ctx context.Context, in *UtxoInsFromDataRequest, opts ...grpc.CallOption) (*UtxoInsResponse, error)
	GetAccountTxFromData(ctx context.Context, in *TxFromDataRequest, opts ...grpc.CallOption) (*AccountTxResponse, error)
	GetUtxoTxFromData(ctx context.Context, in *TxFromDataRequest, opts ...grpc.CallOption) (*UtxoTxResponse, error)
	GetAccountTxFromSignedData(ctx context.Context, in *TxFromSignedDataRequest, opts ...grpc.CallOption) (*AccountTxResponse, error)
	GetUtxoTxFromSignedData(ctx context.Context, in *TxFromSignedDataRequest, opts ...grpc.CallOption) (*UtxoTxResponse, error)
	CreateAccountSignedTx(ctx context.Context, in *CreateAccountSignedTxRequest, opts ...grpc.CallOption) (*CreateSignedTxResponse, error)
	CreateAccountTx(ctx context.Context, in *CreateAccountTxRequest, opts ...grpc.CallOption) (*CreateAccountTxResponse, error)
	CreateUtxoSignedTx(ctx context.Context, in *CreateUtxoSignedTxRequest, opts ...grpc.CallOption) (*CreateSignedTxResponse, error)
	CreateUtxoTx(ctx context.Context, in *CreateUtxoTxRequest, opts ...grpc.CallOption) (*CreateUtxoTxResponse, error)
	VerifyAccountSignedTx(ctx context.Context, in *VerifySignedTxRequest, opts ...grpc.CallOption) (*VerifySignedTxResponse, error)
	VerifyUtxoSignedTx(ctx context.Context, in *VerifySignedTxRequest, opts ...grpc.CallOption) (*VerifySignedTxResponse, error)
	ABIBinToJSON(ctx context.Context, in *ABIBinToJSONRequest, opts ...grpc.CallOption) (*ABIBinToJSONResponse, error)
	ABIJSONToBin(ctx context.Context, in *ABIJSONToBinRequest, opts ...grpc.CallOption) (*ABIJSONToBinResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetSupportCoins(ctx context.Context, in *SupportCoinsRequest, opts ...grpc.CallOption) (*SupportCoinsResponse, error) {
	out := new(SupportCoinsResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getSupportCoins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ConvertAddress(ctx context.Context, in *ConvertAddressRequest, opts ...grpc.CallOption) (*ConvertAddressResponse, error) {
	out := new(ConvertAddressResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/convertAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ValidAddress(ctx context.Context, in *ValidAddressRequest, opts ...grpc.CallOption) (*ValidAddressResponse, error) {
	out := new(ValidAddressResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/validAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetNonce(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error) {
	out := new(NonceResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getNonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetGasPrice(ctx context.Context, in *GasPriceRequest, opts ...grpc.CallOption) (*GasPriceResponse, error) {
	out := new(GasPriceResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getGasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetMinRent(ctx context.Context, in *MinRentRequest, opts ...grpc.CallOption) (*MinRentResponse, error) {
	out := new(MinRentResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getMinRent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SendTx(ctx context.Context, in *SendTxRequest, opts ...grpc.CallOption) (*SendTxResponse, error) {
	out := new(SendTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/SendTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetTxByAddress(ctx context.Context, in *TxAddressRequest, opts ...grpc.CallOption) (*TxAddressResponse, error) {
	out := new(TxAddressResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getTxByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetTxByHash(ctx context.Context, in *TxHashRequest, opts ...grpc.CallOption) (*TxHashResponse, error) {
	out := new(TxHashResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getTxByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetUtxo(ctx context.Context, in *UtxoRequest, opts ...grpc.CallOption) (*UtxoResponse, error) {
	out := new(UtxoResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getUtxo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetUnspentOutputs(ctx context.Context, in *UnspentOutputsRequest, opts ...grpc.CallOption) (*UnspentOutputsResponse, error) {
	out := new(UnspentOutputsResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getUnspentOutputs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetUtxoInsFromData(ctx context.Context, in *UtxoInsFromDataRequest, opts ...grpc.CallOption) (*UtxoInsResponse, error) {
	out := new(UtxoInsResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getUtxoInsFromData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetAccountTxFromData(ctx context.Context, in *TxFromDataRequest, opts ...grpc.CallOption) (*AccountTxResponse, error) {
	out := new(AccountTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getAccountTxFromData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetUtxoTxFromData(ctx context.Context, in *TxFromDataRequest, opts ...grpc.CallOption) (*UtxoTxResponse, error) {
	out := new(UtxoTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getUtxoTxFromData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetAccountTxFromSignedData(ctx context.Context, in *TxFromSignedDataRequest, opts ...grpc.CallOption) (*AccountTxResponse, error) {
	out := new(AccountTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/getAccountTxFromSignedData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetUtxoTxFromSignedData(ctx context.Context, in *TxFromSignedDataRequest, opts ...grpc.CallOption) (*UtxoTxResponse, error) {
	out := new(UtxoTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/GetUtxoTxFromSignedData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateAccountSignedTx(ctx context.Context, in *CreateAccountSignedTxRequest, opts ...grpc.CallOption) (*CreateSignedTxResponse, error) {
	out := new(CreateSignedTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/createAccountSignedTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateAccountTx(ctx context.Context, in *CreateAccountTxRequest, opts ...grpc.CallOption) (*CreateAccountTxResponse, error) {
	out := new(CreateAccountTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/createAccountTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateUtxoSignedTx(ctx context.Context, in *CreateUtxoSignedTxRequest, opts ...grpc.CallOption) (*CreateSignedTxResponse, error) {
	out := new(CreateSignedTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/createUtxoSignedTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateUtxoTx(ctx context.Context, in *CreateUtxoTxRequest, opts ...grpc.CallOption) (*CreateUtxoTxResponse, error) {
	out := new(CreateUtxoTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/createUtxoTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) VerifyAccountSignedTx(ctx context.Context, in *VerifySignedTxRequest, opts ...grpc.CallOption) (*VerifySignedTxResponse, error) {
	out := new(VerifySignedTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/verifyAccountSignedTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) VerifyUtxoSignedTx(ctx context.Context, in *VerifySignedTxRequest, opts ...grpc.CallOption) (*VerifySignedTxResponse, error) {
	out := new(VerifySignedTxResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/verifyUtxoSignedTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ABIBinToJSON(ctx context.Context, in *ABIBinToJSONRequest, opts ...grpc.CallOption) (*ABIBinToJSONResponse, error) {
	out := new(ABIBinToJSONResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/ABIBinToJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ABIJSONToBin(ctx context.Context, in *ABIJSONToBinRequest, opts ...grpc.CallOption) (*ABIJSONToBinResponse, error) {
	out := new(ABIJSONToBinResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.wallet.WalletService/ABIJSONToBin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility
type WalletServiceServer interface {
	GetSupportCoins(context.Context, *SupportCoinsRequest) (*SupportCoinsResponse, error)
	ConvertAddress(context.Context, *ConvertAddressRequest) (*ConvertAddressResponse, error)
	ValidAddress(context.Context, *ValidAddressRequest) (*ValidAddressResponse, error)
	GetBlock(context.Context, *BlockRequest) (*BlockResponse, error)
	GetNonce(context.Context, *NonceRequest) (*NonceResponse, error)
	GetGasPrice(context.Context, *GasPriceRequest) (*GasPriceResponse, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	GetAccount(context.Context, *AccountRequest) (*AccountResponse, error)
	GetMinRent(context.Context, *MinRentRequest) (*MinRentResponse, error)
	SendTx(context.Context, *SendTxRequest) (*SendTxResponse, error)
	GetTxByAddress(context.Context, *TxAddressRequest) (*TxAddressResponse, error)
	GetTxByHash(context.Context, *TxHashRequest) (*TxHashResponse, error)
	GetUtxo(context.Context, *UtxoRequest) (*UtxoResponse, error)
	GetUnspentOutputs(context.Context, *UnspentOutputsRequest) (*UnspentOutputsResponse, error)
	GetUtxoInsFromData(context.Context, *UtxoInsFromDataRequest) (*UtxoInsResponse, error)
	GetAccountTxFromData(context.Context, *TxFromDataRequest) (*AccountTxResponse, error)
	GetUtxoTxFromData(context.Context, *TxFromDataRequest) (*UtxoTxResponse, error)
	GetAccountTxFromSignedData(context.Context, *TxFromSignedDataRequest) (*AccountTxResponse, error)
	GetUtxoTxFromSignedData(context.Context, *TxFromSignedDataRequest) (*UtxoTxResponse, error)
	CreateAccountSignedTx(context.Context, *CreateAccountSignedTxRequest) (*CreateSignedTxResponse, error)
	CreateAccountTx(context.Context, *CreateAccountTxRequest) (*CreateAccountTxResponse, error)
	CreateUtxoSignedTx(context.Context, *CreateUtxoSignedTxRequest) (*CreateSignedTxResponse, error)
	CreateUtxoTx(context.Context, *CreateUtxoTxRequest) (*CreateUtxoTxResponse, error)
	VerifyAccountSignedTx(context.Context, *VerifySignedTxRequest) (*VerifySignedTxResponse, error)
	VerifyUtxoSignedTx(context.Context, *VerifySignedTxRequest) (*VerifySignedTxResponse, error)
	ABIBinToJSON(context.Context, *ABIBinToJSONRequest) (*ABIBinToJSONResponse, error)
	ABIJSONToBin(context.Context, *ABIJSONToBinRequest) (*ABIJSONToBinResponse, error)
}

// UnimplementedWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (UnimplementedWalletServiceServer) GetSupportCoins(context.Context, *SupportCoinsRequest) (*SupportCoinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportCoins not implemented")
}
func (UnimplementedWalletServiceServer) ConvertAddress(context.Context, *ConvertAddressRequest) (*ConvertAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertAddress not implemented")
}
func (UnimplementedWalletServiceServer) ValidAddress(context.Context, *ValidAddressRequest) (*ValidAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidAddress not implemented")
}
func (UnimplementedWalletServiceServer) GetBlock(context.Context, *BlockRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedWalletServiceServer) GetNonce(context.Context, *NonceRequest) (*NonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonce not implemented")
}
func (UnimplementedWalletServiceServer) GetGasPrice(context.Context, *GasPriceRequest) (*GasPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGasPrice not implemented")
}
func (UnimplementedWalletServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServiceServer) GetAccount(context.Context, *AccountRequest) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedWalletServiceServer) GetMinRent(context.Context, *MinRentRequest) (*MinRentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinRent not implemented")
}
func (UnimplementedWalletServiceServer) SendTx(context.Context, *SendTxRequest) (*SendTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTx not implemented")
}
func (UnimplementedWalletServiceServer) GetTxByAddress(context.Context, *TxAddressRequest) (*TxAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByAddress not implemented")
}
func (UnimplementedWalletServiceServer) GetTxByHash(context.Context, *TxHashRequest) (*TxHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByHash not implemented")
}
func (UnimplementedWalletServiceServer) GetUtxo(context.Context, *UtxoRequest) (*UtxoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtxo not implemented")
}
func (UnimplementedWalletServiceServer) GetUnspentOutputs(context.Context, *UnspentOutputsRequest) (*UnspentOutputsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnspentOutputs not implemented")
}
func (UnimplementedWalletServiceServer) GetUtxoInsFromData(context.Context, *UtxoInsFromDataRequest) (*UtxoInsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtxoInsFromData not implemented")
}
func (UnimplementedWalletServiceServer) GetAccountTxFromData(context.Context, *TxFromDataRequest) (*AccountTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTxFromData not implemented")
}
func (UnimplementedWalletServiceServer) GetUtxoTxFromData(context.Context, *TxFromDataRequest) (*UtxoTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtxoTxFromData not implemented")
}
func (UnimplementedWalletServiceServer) GetAccountTxFromSignedData(context.Context, *TxFromSignedDataRequest) (*AccountTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTxFromSignedData not implemented")
}
func (UnimplementedWalletServiceServer) GetUtxoTxFromSignedData(context.Context, *TxFromSignedDataRequest) (*UtxoTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtxoTxFromSignedData not implemented")
}
func (UnimplementedWalletServiceServer) CreateAccountSignedTx(context.Context, *CreateAccountSignedTxRequest) (*CreateSignedTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountSignedTx not implemented")
}
func (UnimplementedWalletServiceServer) CreateAccountTx(context.Context, *CreateAccountTxRequest) (*CreateAccountTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountTx not implemented")
}
func (UnimplementedWalletServiceServer) CreateUtxoSignedTx(context.Context, *CreateUtxoSignedTxRequest) (*CreateSignedTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUtxoSignedTx not implemented")
}
func (UnimplementedWalletServiceServer) CreateUtxoTx(context.Context, *CreateUtxoTxRequest) (*CreateUtxoTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUtxoTx not implemented")
}
func (UnimplementedWalletServiceServer) VerifyAccountSignedTx(context.Context, *VerifySignedTxRequest) (*VerifySignedTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAccountSignedTx not implemented")
}
func (UnimplementedWalletServiceServer) VerifyUtxoSignedTx(context.Context, *VerifySignedTxRequest) (*VerifySignedTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUtxoSignedTx not implemented")
}
func (UnimplementedWalletServiceServer) ABIBinToJSON(context.Context, *ABIBinToJSONRequest) (*ABIBinToJSONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ABIBinToJSON not implemented")
}
func (UnimplementedWalletServiceServer) ABIJSONToBin(context.Context, *ABIJSONToBinRequest) (*ABIJSONToBinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ABIJSONToBin not implemented")
}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetSupportCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportCoinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetSupportCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getSupportCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetSupportCoins(ctx, req.(*SupportCoinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ConvertAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ConvertAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/convertAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ConvertAddress(ctx, req.(*ConvertAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ValidAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ValidAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/validAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ValidAddress(ctx, req.(*ValidAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBlock(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getNonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetNonce(ctx, req.(*NonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getGasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetGasPrice(ctx, req.(*GasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetMinRent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinRentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetMinRent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getMinRent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetMinRent(ctx, req.(*MinRentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SendTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/SendTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SendTx(ctx, req.(*SendTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetTxByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetTxByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getTxByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetTxByAddress(ctx, req.(*TxAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetTxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetTxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getTxByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetTxByHash(ctx, req.(*TxHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetUtxo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UtxoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUtxo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getUtxo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUtxo(ctx, req.(*UtxoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetUnspentOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnspentOutputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUnspentOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getUnspentOutputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUnspentOutputs(ctx, req.(*UnspentOutputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetUtxoInsFromData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UtxoInsFromDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUtxoInsFromData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getUtxoInsFromData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUtxoInsFromData(ctx, req.(*UtxoInsFromDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetAccountTxFromData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxFromDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAccountTxFromData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getAccountTxFromData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAccountTxFromData(ctx, req.(*TxFromDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetUtxoTxFromData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxFromDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUtxoTxFromData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getUtxoTxFromData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUtxoTxFromData(ctx, req.(*TxFromDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetAccountTxFromSignedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxFromSignedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAccountTxFromSignedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/getAccountTxFromSignedData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAccountTxFromSignedData(ctx, req.(*TxFromSignedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetUtxoTxFromSignedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxFromSignedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUtxoTxFromSignedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/GetUtxoTxFromSignedData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUtxoTxFromSignedData(ctx, req.(*TxFromSignedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateAccountSignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountSignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateAccountSignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/createAccountSignedTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateAccountSignedTx(ctx, req.(*CreateAccountSignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateAccountTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateAccountTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/createAccountTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateAccountTx(ctx, req.(*CreateAccountTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateUtxoSignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUtxoSignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateUtxoSignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/createUtxoSignedTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateUtxoSignedTx(ctx, req.(*CreateUtxoSignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateUtxoTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUtxoTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateUtxoTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/createUtxoTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateUtxoTx(ctx, req.(*CreateUtxoTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_VerifyAccountSignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).VerifyAccountSignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/verifyAccountSignedTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).VerifyAccountSignedTx(ctx, req.(*VerifySignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_VerifyUtxoSignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).VerifyUtxoSignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/verifyUtxoSignedTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).VerifyUtxoSignedTx(ctx, req.(*VerifySignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ABIBinToJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABIBinToJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ABIBinToJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/ABIBinToJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ABIBinToJSON(ctx, req.(*ABIBinToJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ABIJSONToBin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABIJSONToBinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ABIJSONToBin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.wallet.WalletService/ABIJSONToBin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ABIJSONToBin(ctx, req.(*ABIJSONToBinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "savourrpc.wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSupportCoins",
			Handler:    _WalletService_GetSupportCoins_Handler,
		},
		{
			MethodName: "convertAddress",
			Handler:    _WalletService_ConvertAddress_Handler,
		},
		{
			MethodName: "validAddress",
			Handler:    _WalletService_ValidAddress_Handler,
		},
		{
			MethodName: "getBlock",
			Handler:    _WalletService_GetBlock_Handler,
		},
		{
			MethodName: "getNonce",
			Handler:    _WalletService_GetNonce_Handler,
		},
		{
			MethodName: "getGasPrice",
			Handler:    _WalletService_GetGasPrice_Handler,
		},
		{
			MethodName: "getBalance",
			Handler:    _WalletService_GetBalance_Handler,
		},
		{
			MethodName: "getAccount",
			Handler:    _WalletService_GetAccount_Handler,
		},
		{
			MethodName: "getMinRent",
			Handler:    _WalletService_GetMinRent_Handler,
		},
		{
			MethodName: "SendTx",
			Handler:    _WalletService_SendTx_Handler,
		},
		{
			MethodName: "getTxByAddress",
			Handler:    _WalletService_GetTxByAddress_Handler,
		},
		{
			MethodName: "getTxByHash",
			Handler:    _WalletService_GetTxByHash_Handler,
		},
		{
			MethodName: "getUtxo",
			Handler:    _WalletService_GetUtxo_Handler,
		},
		{
			MethodName: "getUnspentOutputs",
			Handler:    _WalletService_GetUnspentOutputs_Handler,
		},
		{
			MethodName: "getUtxoInsFromData",
			Handler:    _WalletService_GetUtxoInsFromData_Handler,
		},
		{
			MethodName: "getAccountTxFromData",
			Handler:    _WalletService_GetAccountTxFromData_Handler,
		},
		{
			MethodName: "getUtxoTxFromData",
			Handler:    _WalletService_GetUtxoTxFromData_Handler,
		},
		{
			MethodName: "getAccountTxFromSignedData",
			Handler:    _WalletService_GetAccountTxFromSignedData_Handler,
		},
		{
			MethodName: "GetUtxoTxFromSignedData",
			Handler:    _WalletService_GetUtxoTxFromSignedData_Handler,
		},
		{
			MethodName: "createAccountSignedTx",
			Handler:    _WalletService_CreateAccountSignedTx_Handler,
		},
		{
			MethodName: "createAccountTx",
			Handler:    _WalletService_CreateAccountTx_Handler,
		},
		{
			MethodName: "createUtxoSignedTx",
			Handler:    _WalletService_CreateUtxoSignedTx_Handler,
		},
		{
			MethodName: "createUtxoTx",
			Handler:    _WalletService_CreateUtxoTx_Handler,
		},
		{
			MethodName: "verifyAccountSignedTx",
			Handler:    _WalletService_VerifyAccountSignedTx_Handler,
		},
		{
			MethodName: "verifyUtxoSignedTx",
			Handler:    _WalletService_VerifyUtxoSignedTx_Handler,
		},
		{
			MethodName: "ABIBinToJSON",
			Handler:    _WalletService_ABIBinToJSON_Handler,
		},
		{
			MethodName: "ABIJSONToBin",
			Handler:    _WalletService_ABIJSONToBin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "savourrpc/wallet.proto",
}
